---
# We just wrap `build` so this is really it
name: "jellyfin-ffmpeg"
version: "5.1.2-9"
packages:
  - buster-amd64
  - buster-armhf
  - buster-arm64
  - bullseye-amd64
  - bullseye-armhf
  - bullseye-arm64
  - bionic-amd64
  - bionic-armhf
  - bionic-arm64
  - focal-amd64
  - focal-armhf
  - focal-arm64
  - jammy-amd64
  - jammy-armhf
  - jammy-arm64
  - kinetic-amd64
  - kinetic-armhf
  - kinetic-arm64
