/*
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef FFTOOLS_FFPROBE_H
#define FFTOOLS_FFPROBE_H

#include "textformat/avtextformat.h"

typedef enum {
    SECTION_ID_CHAPTER,
    SECTION_ID_CHAPTER_TAGS,
    SECTION_ID_CHAPTERS,
    SECTION_ID_ERROR,
    SECTION_ID_FORMAT,
    SECTION_ID_FORMAT_TAGS,
    SECTION_ID_FRAME,
    SECTION_ID_FRAMES,
    SECTION_ID_FRAME_TAGS,
    SECTION_ID_FRAME_SIDE_DATA_LIST,
    SECTION_ID_FRAME_SIDE_DATA,
    SECTION_ID_FRAME_SIDE_DATA_TIMECODE_LIST,
    SECTION_ID_FRAME_SIDE_DATA_TIMECODE,
    SECTION_ID_FRAME_SIDE_DATA_COMPONENT_LIST,
    SECTION_ID_FRAME_SIDE_DATA_COMPONENT,
    SECTION_ID_FRAME_SIDE_DATA_PIECE_LIST,
    SECTION_ID_FRAME_SIDE_DATA_PIECE,
    SECTION_ID_FRAME_LOG,
    SECTION_ID_FRAME_LOGS,
    SECTION_ID_LIBRARY_VERSION,
    SECTION_ID_LIBRARY_VERSIONS,
    SECTION_ID_PACKET,
    SECTION_ID_PACKET_TAGS,
    SECTION_ID_PACKETS,
    SECTION_ID_PACKETS_AND_FRAMES,
    SECTION_ID_PACKET_SIDE_DATA_LIST,
    SECTION_ID_PACKET_SIDE_DATA,
    SECTION_ID_PIXEL_FORMAT,
    SECTION_ID_PIXEL_FORMAT_FLAGS,
    SECTION_ID_PIXEL_FORMAT_COMPONENT,
    SECTION_ID_PIXEL_FORMAT_COMPONENTS,
    SECTION_ID_PIXEL_FORMATS,
    SECTION_ID_PROGRAM_STREAM_DISPOSITION,
    SECTION_ID_PROGRAM_STREAM_TAGS,
    SECTION_ID_PROGRAM,
    SECTION_ID_PROGRAM_STREAMS,
    SECTION_ID_PROGRAM_STREAM,
    SECTION_ID_PROGRAM_TAGS,
    SECTION_ID_PROGRAM_VERSION,
    SECTION_ID_PROGRAMS,
    SECTION_ID_STREAM_GROUP_STREAM_DISPOSITION,
    SECTION_ID_STREAM_GROUP_STREAM_TAGS,
    SECTION_ID_STREAM_GROUP,
    SECTION_ID_STREAM_GROUP_COMPONENTS,
    SECTION_ID_STREAM_GROUP_COMPONENT,
    SECTION_ID_STREAM_GROUP_SUBCOMPONENTS,
    SECTION_ID_STREAM_GROUP_SUBCOMPONENT,
    SECTION_ID_STREAM_GROUP_PIECES,
    SECTION_ID_STREAM_GROUP_PIECE,
    SECTION_ID_STREAM_GROUP_SUBPIECES,
    SECTION_ID_STREAM_GROUP_SUBPIECE,
    SECTION_ID_STREAM_GROUP_BLOCKS,
    SECTION_ID_STREAM_GROUP_BLOCK,
    SECTION_ID_STREAM_GROUP_STREAMS,
    SECTION_ID_STREAM_GROUP_STREAM,
    SECTION_ID_STREAM_GROUP_DISPOSITION,
    SECTION_ID_STREAM_GROUP_TAGS,
    SECTION_ID_STREAM_GROUPS,
    SECTION_ID_ROOT,
    SECTION_ID_STREAM,
    SECTION_ID_STREAM_DISPOSITION,
    SECTION_ID_STREAMS,
    SECTION_ID_STREAM_TAGS,
    SECTION_ID_STREAM_SIDE_DATA_LIST,
    SECTION_ID_STREAM_SIDE_DATA,
    SECTION_ID_SUBTITLE,

    // hwaccel
    SECTION_ID_HWACCEL_DEVICES,
    SECTION_ID_HWACCEL_DEVICE,

    SECTION_ID_DEVICE_PATH_DRM,
    SECTION_ID_DEVICE_INDEX_D3D11VA,
    SECTION_ID_DEVICE_INDEX_CUDA,

    SECTION_ID_DEVICE_INFO_DRM,
    SECTION_ID_DEVICE_INFO_VAAPI,
    SECTION_ID_DEVICE_INFO_D3D11VA,
    SECTION_ID_DEVICE_INFO_QSV,
    SECTION_ID_DEVICE_INFO_OPENCL,
    SECTION_ID_DEVICE_INFO_VULKAN,
    SECTION_ID_DEVICE_INFO_CUDA,
    SECTION_ID_DEVICE_INFO_AMF,

    SECTION_ID_DEVICE_UTIL_DRM,
    SECTION_ID_DEVICE_UTIL_D3D11VA,
    SECTION_ID_DEVICE_UTIL_CUDA,

    SECTION_ID_DEVICE_DECODERS_VAAPI,
    SECTION_ID_DEVICE_DECODERS_D3D11VA,
    SECTION_ID_DEVICE_DECODERS_QSV,
    SECTION_ID_DEVICE_DECODERS_CUDA,
    SECTION_ID_DEVICE_DECODER,

    SECTION_ID_DEVICE_ENCODERS_VAAPI,
    SECTION_ID_DEVICE_ENCODERS_QSV,
    SECTION_ID_DEVICE_ENCODERS_CUDA,
    SECTION_ID_DEVICE_ENCODERS_AMF,
    SECTION_ID_DEVICE_ENCODERS_MF,
    SECTION_ID_DEVICE_ENCODER,

    SECTION_ID_DEVICE_FILTERS_VAAPI,
    SECTION_ID_DEVICE_FILTERS_QSV,
    SECTION_ID_DEVICE_FILTER,

    SECTION_ID_DEVICE_PROFILES,
    SECTION_ID_DEVICE_PROFILE,
    SECTION_ID_DEVICE_PIX_FMTS,
    SECTION_ID_DEVICE_PIX_FMT,
    SECTION_ID_DEVICE_PRESETS,
    SECTION_ID_DEVICE_PRESET,
} SectionID;

extern const AVTextFormatSection sections[];

void mark_section_show_entries(SectionID section_id,
                               int show_all_entries, AVDictionary *entries);

#endif /* FFTOOLS_FFPROBE_H */
