name: Build jellyfin-ffmpeg

on:
  push:
    branches:
      - jellyfin

  pull_request:
    branches:
      - jellyfin

  workflow_dispatch:

jobs:
  build_linux:
    name: Build ${{ matrix.release }} ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        release:
          - bullseye
          - buster
          - stretch
          - groovy
          - focal
          - bionic

        arch:
          - amd64
          - arm64
          - armhf

    steps:
      - uses: actions/checkout@v2

      - name: Install make and mmv
        run: sudo apt-get install make mmv

      - name: Build
        run: ./build ${{ matrix.release }} ${{ matrix.arch }} dist

      - name: Upload Packages
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ matrix.release }} ${{ matrix.arch }} package
          path: dist
  build_win64:
    name: Build windows win64
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install make

      - name: Build
        run: ./build-win64 dist

      - name: Upload Packages
        uses: actions/upload-artifact@v2.2.3
        with:
          name: windows win64 package
          path: dist
